server:
  port: 8999

spring:
  application:
    name: movie-backend
  flyway:
    enabled: false
    locations: classpath:db/flyway-migration


  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog/db.changelog-master.xml
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}

  jpa:
    hibernate:
      ddl-auto: validate # validation by Hibernate
    open-in-view: false

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver