server:
  port: 8080

spring:
  application:
    name: movie-backend
  flyway:
    enabled: false
    locations: classpath:db/flyway-migration


  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog/db.changelog-master.xml
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}

  jpa:
    hibernate:
      ddl-auto: validate # validation by Hibernate
    open-in-view: false

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

app:
  external-api:
    base-url: https://nodejs-develop-5290.up.railway.app
    api-key: ${EXTERNAL_API_KEY:changeme}
    api-key-header: API_KEY
